[package]
name = "vzdump-browser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
crossterm = "0.28"
ratatui = "0.29"
chrono = "0.4"
ext4_rs = "1.3"
fatfs = "0.3"
sha2 = "0.10"
hex = "0.4"

[patch.crates-io]
ext4_rs = { git = "https://github.com/v0l/ext4_rs.git" }
